"""add cameras table

Revision ID: 0907b88cc740
Revises: 963fe387042b
Create Date: 2026-07-05 10:43:07.197569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0907b88cc740'
down_revision: Union[str, None] = '963fe387042b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table de configuration des caméras (gérée par l'administrateur via l'API).
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('line_x1', sa.Integer(), nullable=True),
    sa.Column('line_y1', sa.Integer(), nullable=True),
    sa.Column('line_x2', sa.Integer(), nullable=True),
    sa.Column('line_y2', sa.Integer(), nullable=True),
    sa.Column('crossing_direction', sa.Enum('TOP_TO_BOTTOM_IS_ENTRY', 'BOTTOM_TO_TOP_IS_ENTRY', name='crossingdirection'), nullable=False),
    sa.Column('min_crossing_frames', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('present_threshold', sa.Float(), nullable=False),
    sa.Column('late_threshold', sa.Float(), nullable=False),
    sa.Column('face_match_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    # Le type ENUM PostgreSQL n'est pas supprimé automatiquement avec la table :
    # on le retire explicitement pour que le downgrade soit complet.
    op.execute("DROP TYPE IF EXISTS crossingdirection")
    # ### end Alembic commands ###
