"""init schema

Revision ID: 963fe387042b
Revises: 
Create Date: 2026-07-04 21:29:38.167187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


revision: str = '963fe387042b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Extension requise par la colonne face_embedding (pgvector).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_type', sa.Enum('SESSION', 'BREAK', name='sessiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('face_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attendance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'ABSENT', name='attendancestatus'), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'schedule_id', 'result_date', name='uq_presence_unique')
    )
    op.create_index(op.f('ix_attendance_results_result_date'), 'attendance_results', ['result_date'], unique=False)
    op.create_index(op.f('ix_attendance_results_schedule_id'), 'attendance_results', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_attendance_results_student_id'), 'attendance_results', ['student_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('event_type', sa.Enum('ENTRY', 'EXIT', name='eventtype'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_student_id'), 'snapshots', ['student_id'], unique=False)
    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ENTRY', 'EXIT', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_student_id'), 'attendance_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_timestamp'), 'attendance_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_events_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_student_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_snapshots_student_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_attendance_results_student_id'), table_name='attendance_results')
    op.drop_index(op.f('ix_attendance_results_schedule_id'), table_name='attendance_results')
    op.drop_index(op.f('ix_attendance_results_result_date'), table_name='attendance_results')
    op.drop_table('attendance_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_table('students')
    op.drop_table('schedules')
    # Les types ENUM PostgreSQL ne sont pas supprimés automatiquement avec les
    # tables : on les retire explicitement pour que le downgrade soit complet.
    op.execute("DROP TYPE IF EXISTS eventtype")
    op.execute("DROP TYPE IF EXISTS attendancestatus")
    op.execute("DROP TYPE IF EXISTS sessiontype")
    # ### end Alembic commands ###
